### ISSUE TITLE
facts get automatically deleted at every puppet agent -t run

### ISSUE THREAD

**Issue by fduranti** [waveclaw/puppet-facter_cacheable#1]
Hi, I'm using puppet enterprise 2016.2. 
I'm using your subscription-manager modules (I had some issue I'll report on it's git repository later) and it seems that the facts created using this module get automatically deleted at the first run because they're in the default pluginsync fact directory.
This is the start of the run and it happen at every run. 
[root@itnaptpupl01 bin]# puppet agent -t
Info: Using configured environment 'development'
Info: Retrieving pluginfacts
Notice: /File[/opt/puppetlabs/puppet/cache/facts.d/rhsm_available_pools.yaml]/ensure: removed
Notice: /File[/opt/puppetlabs/puppet/cache/facts.d/rhsm_available_repos.yaml]/ensure: removed
Notice: /File[/opt/puppetlabs/puppet/cache/facts.d/rhsm_disabled_pools.yaml]/ensure: removed
Notice: /File[/opt/puppetlabs/puppet/cache/facts.d/rhsm_disabled_repos.yaml]/ensure: removed
Notice: /File[/opt/puppetlabs/puppet/cache/facts.d/rhsm_enabled_pools.yaml]/ensure: removed
Notice: /File[/opt/puppetlabs/puppet/cache/facts.d/rhsm_enabled_repos.yaml]/ensure: removed
Info: Retrieving plugin

It seems that some directory should be excluded to make the cache work.
The for cycle seems to get that directory first and it will simply use it but at the next run file get deleted.

I've commented those part of the code to use the "default" /etc/facter/facts.d but I see there's some comment in the code to exclude some directory... probably they could be uncommented:

+++ /tmp/puppet-file20160826-5310-uy4wy9	2016-08-26 10:06:44.067726655 +0200
@@ -85,17 +85,17 @@
     def get_cache(key, source)
        if ! source
          cache_dir = '/etc/facter/facts.d'
-         if Puppet.features.external_facts?
-           for dir in Facter.search_external_path
-             # the plugin facts directory in /var/lib is cleaned each run
-             if (File.exist?(dir)) #and
-               #dir != '/var/lib/puppet/facts.d' and
-               #dir != '/opt/puppetlabs/puppet/cache/facts.d/') # PE 2015 location
-               cache_dir = dir
-               break
-             end
-           end
-         end
+#         if Puppet.features.external_facts?
+#           for dir in Facter.search_external_path
+#             # the plugin facts directory in /var/lib is cleaned each run
+#             if (File.exist?(dir)) #and
+#               #dir != '/var/lib/puppet/facts.d' and
+#               #dir != '/opt/puppetlabs/puppet/cache/facts.d/') # PE 2015 location
+#               cache_dir = dir
+#               break
+#             end
+#           end
+#         end
          keystring = key.to_s
          cache_file = "#{cache_dir}/#{keystring}.yaml"
        else

I also had to add the creation of /etc/facter because Dir.mkdir(cache_dir) don't create it it the facter_cacheable.rb:
    # Write out a cache of data
    # @param key string The identifier for the data
    # @param ttl integer Time-to-live in seconds which defauls to 1 hr (3600)
    # @param source string Fully-qualified path to altnerative YAML file
    # @return [object] Cached value (hash, string, array, number, etc)
    # @api public
    def cache(key, value, source = nil)
       if key && value
         mycache = get_cache(key, source)
         cache_file = mycache[:file]
         cache_dir = mycache[:dir]
         begin
+           if !File::exist?('/etc/facter')
+                Dir.mkdir('/etc/facter')
+           end
           if !File::exist?(cache_dir)
                Dir.mkdir(cache_dir)
           end
           # don't use the Rubyist standard pattern so we can test with rspec
           out = File.open(cache_file, 'w')
           YAML.dump({(key.to_s) => value}, out)
           out.close()
         rescue Exception => e
           Facter.debug("#{e.backtrace[0]}: #{$!}.")
         end
       end
    end

**Comment by waveclaw** [comment]
This is a known issue from the README.  I will update the documentation to be more clear about what Puppet Enterprise does.

Unfortunately the copy-pasted code you provided is a mess.  It looks like you tried to paste in unified diff output.  GitHub reformatted it to markdown. Since you did not put it inside of code blocks it is a mess  I am unable and unwilling to untangle this. Can you provide an actual push request with your changes?

For the issue with PE 2016.2 on subscription-manager, I closed your request.  Puppet 2016.2 and later is not supported. The environment keyword is unused but reserved in Puppet 4.4.1 and later.  That will require a 3.0 version of the module to break existing API.

Closing with wontfix pending and update.
