### ISSUE TITLE
Forge release?

### ISSUE THREAD

**Issue by fduranti** [waveclaw/puppet-facter_cacheable#3]
Hi, can you do a forge release with the last changes so it could be get directly from the forge?

Thanks
Francesco

**Comment by waveclaw** [comment]
I just validated 2.2.2 today against Satellite 6.1 and posted that to the forge.

Version 2.2.2 should be the last Puppet 3 release.

All my time is dedicated to getting a good test with version 3.0.0 on Puppet 4 with katello.

I've already validated Satellite 6.1 with Puppet 4 on Satellite 6.1.
