### ISSUE TITLE
external_facts feature removed as of puppet 5.0.0

### ISSUE THREAD

**Issue by Renelast** [waveclaw/puppet-facter_cacheable#7]
Please see [This puppet issue]( https://tickets.puppetlabs.com/browse/PUP-6481)

The external_facts feature is removed from puppet 5 onwards.
The facter_cacheable feature makes use of the external_facts feature to enable itself.
Therefor on puppet 5 facter_cacheable does no longer work.

A simple workaround (that I have implemented in our environment) could be to check the puppet version you're running on.
If it's puppet 5 or up you can enable the facter_cacheable feature.

` if (Puppet::Util::Package.versioncmp(Puppet.version, "5.0.0") > 0) or Puppet.features.external_facts?`

This works in our environment but I'm not 100% certain whether this is the best solution.

**Comment by waveclaw** [comment]
The PR for this cannot be merged directly due to the massive number of failures.

I will try to rework this and manually merge your changes with additional testing and Puppet 5 support.
